name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:4.5.1

    steps:
      - uses: actions/checkout@v4

      - name: Show R version
        run: Rscript -e 'R.version.string'

